project:
  type: website

website:
  title: "Mr De Bonis"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Mr-DeBonis
      - icon: linkedin
        href: https://www.linkedin.com/in/ignacio-de-bonis/
format:
  html:
    theme: united
    css: styles.css



